apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-gate-latest
  labels:
    micro: runtime
    name: gate
    version: latest
  annotations:
    name: "gate"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-gate
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-gate
        micro: runtime
        version: latest
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9000"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - micro-api
                    - key: micro
                      operator: In
                      values:
                        - runtime
                topologyKey: "kubernetes.io/hostname"
      
      
      containers:
      - name: micro
        env:
        - name: MICRO_API_RESOLVER
          value: subdomain
        - name: MICRO_AUTH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_public_key
        - name: MICRO_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_private_key
        - name: MICRO_PROFILE
          value: "client"
        - name: MICRO_SERVICE_NAME
          value: gate
        - name: MICRO_PROXY
          value: "micro-network.default.svc.cluster.local:8443"
        - name: MICRO_LOG_LEVEL
          value: "debug"
        - name: MICRO_TRACING_REPORTER_ADDRESS
          value: "jaeger-tracing-agent.monitoring.svc.cluster.local:6831"
        args:
        - service
        - gate
        image: mcbeam-hub.tencentcloudcr.com/wolfplus/mcbeam-dev:mcbeam-dev-20210827-39be028afb26dc381060a58092088d213a885299
        imagePullPolicy: Always
        ports:
        - containerPort: 3250
          name: gate-port
        readinessProbe:
          tcpSocket:
            port: gate-port
          initialDelaySeconds: 5
          periodSeconds: 10
