apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-http-latest
  labels:
    micro: runtime
    name: api
    version: latest
  annotations:
    name: "http"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-http
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-http
        micro: runtime
        version: latest
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9000"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - micro-http
                    - key: micro
                      operator: In
                      values:
                        - runtime
                topologyKey: "kubernetes.io/hostname"
      
      
      containers:
      - name: micro
        env:
        - name: MICRO_API_RESOLVER
          value: subdomain
        - name: MICRO_API_HANDLER
          value: http
        - name: MICRO_AUTH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_public_key
        - name: MICRO_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_private_key
        - name: MICRO_PROFILE
          value: "client"
        - name: MICRO_SERVICE_NAME
          value: client
        - name: MICRO_REGISTRY_TLS_CA
          value: "/certs/registry/ca.crt"
        - name: MICRO_REGISTRY_TLS_CERT
          value: "/certs/registry/cert.pem"
        - name: MICRO_REGISTRY_TLS_KEY
          value: "/certs/registry/key.pem"
        - name: MICRO_PROXY
          value: "micro-network.default.svc.cluster.local:8443"
        args:
        - service
        - api
        image: mcbeam-hub.tencentcloudcr.com/wolfplus/mcbeam-dev:mcbeam-dev-20210906-2e1d8150fb32d4a6f44a598395aa8eeb54e6aa27
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: api-port
        readinessProbe:
          tcpSocket:
            port: api-port
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - name: etcd-client-certs
            mountPath: "/certs/registry"
            readOnly: true
      volumes:
        - name: etcd-client-certs
          secret:
            secretName: etcd-client-certs